{
 "title": "Django dashboard final",
 "description": "Django metrics dashboard",
 "tags": [
  "Web",
  "Django",
  "Database"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "auth-service:8001,history-service:8002,tournament-service:8003"
   }
  ]
 },
 "panels": [
  {
   "title": "2XX Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{status=~\"2.+\",instance=\"$service\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "4XX Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{status=~\"4.+\", instance=\"$service\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "5XX Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{status=~\"5.+\", instance=\"$service\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "DB Query Errors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(django_db_errors_total{instance=~\"$service\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Connection Errors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(django_db_new_connection_errors_total{instance=~\"$service\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(django_http_requests_latency_seconds_by_view_method_bucket{instance=\"$service\"}[$__rate_interval])) by (le))",
     "legendFormat": "50 quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(django_http_requests_latency_seconds_by_view_method_bucket{instance=\"$service\"}[$__rate_interval])) by (le))",
     "legendFormat": "95 quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(django_http_requests_latency_seconds_by_view_method_bucket{instance=\"$service\"}[$__rate_interval])) by (le))",
     "legendFormat": "99 quantile"
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{instance=\"$service\"}[$__rate_interval])) by(status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Database Total Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(django_db_execute_total{instance=~\"$service\"}[$__rate_interval])) by (vendor)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(10, sum(irate(django_http_requests_total_by_view_transport_method_total{instance=~\"$service\",view!~\"prometheus-django-metrics|healthcheck|.*shop_product_import_1c_status\"}[$__rate_interval])) by(method, view) > 0)",
     "legendFormat": "{{method}} /{{view}}"
    }
   ]
  },
  {
   "title": "Database Query Duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(django_db_query_duration_seconds_bucket{instance=~\"$service\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}