    # email notification is working fine ##
# global:
#   resolve_timeout: 5m
#   #time to send resolved notification

# route:
#   receiver: 'email'

# receivers:
#   - name: 'email'
#     email_configs:
#     # Whether to notify about resolved alerts.
#       - send_resolved: true
#         # The email address to send notifications to.
#         # Allows a comma separated list of rfc5322 compliant email addresses.
#         to: 'sandruozzo@gmail.com'

#         # The sender's address.
#         from: 'sandruozzo@gmail.com'

#         # The SMTP host through which emails are sent.
#         smarthost: 'smtp.gmail.com:587'

#         # SMTP authentication information.
#         # auth_password and auth_password_file are mutually exclusive.
#         auth_username: 'sandruozzo@gmail.com'
#         # [ auth_password_file: <string> | default = global.smtp_auth_password_file ]
#         auth_password_file: '/etc/alertmanager/smtp_password.txt'
#         #password is stored into this file
#         auth_identity: 'sandruozzo@gmail.com'
#         # # The SMTP TLS requirement.
#         # # Note that Go does not support unencrypted connections to remote SMTP endpoints.
#         require_tls: true
#         # # TLS configuration.
#         tls_config:
#           insecure_skip_verify: false


# global:
#   resolve_timeout: 5m

# route:
#   receiver: 'email'

# receivers:
#   - name: 'email'
#     email_configs:
#       - to: 'sandruozzo@gmail.com'
#         from: 'sandruozzo@gmail.com'
#         smarthost: 'smtp.gmail.com:587'
#         auth_username: 'sandruozzo@gmail.com'
#         auth_identity: 'sandruozzo@gmail.com'
#         auth_password: 'bufcrqptsprivajt'
#         send_resolved: true

## also slack is workings ##
 global:
   resolve_timeout: 1m
   slack_api_url: 'https://hooks.slack.com/services/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'

 route:
   receiver: 'slack-notifications'

 receivers:
 - name: 'slack-notifications'
   slack_configs:
   - channel: '#monitoring-instances'
     send_resolved: true

# https://join.slack.com/t/monitoring-mondo/shared_invite/zt-2yu1pdet0-iiV53gArkUU~fK7~_awq7A
# link invito monitoring https://join.slack.com/t/monitoring-mondo/shared_invite/zt-2yu1pdet0-iiV53gArkUU~fK7~_awq7A

