global:
  resolve_timeout: 3m
  #time to send resolved notification

route:
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - send_resolved: true
        to: 'sandruozzo@gmail.com'
        from: 'sandruozzo@gmail.com'
        smarthost: 'smtp.gmail.com:587'

        auth_username: 'sandruozzo@gmail.com'
        auth_password_file: '/etc/alertmanager/smtp_password.txt'
        #password is stored into this file
        auth_identity: 'sandruozzo@gmail.com'
        require_tls: true
        tls_config:
          insecure_skip_verify: false


## slack is workings ##
# global:
#   resolve_timeout: 3m
#   slack_api_url: 'https://hooks.slack.com/services/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'

# route:
#   receiver: 'slack-notifications'

# receivers:
# - name: 'slack-notifications'
#   slack_configs:
#   - channel: '#monitoring-instances'
#     send_resolved: true
#     icon_url: https://avatars3.githubusercontent.com/u/3380462
#     title: |-
#      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
#      {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
#        {{" "}}(
#        {{- with .CommonLabels.Remove .GroupLabels.Names }}
#          {{- range $index, $label := .SortedPairs -}}
#            {{ if $index }}, {{ end }}
#            {{- $label.Name }}="{{ $label.Value -}}"
#          {{- end }}
#        {{- end -}}
#        )
#      {{- end }}
#     text: >-
#      {{ range .Alerts -}}
#      *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

#      *Description:* {{ .Annotations.description }}

#      *Details:*
#        {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
#        {{ end }}
#      {{ end }}